name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" 
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: generate-snake-game-from-github-contribution-grid
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          # AGREGAMOS ESTO para que pueda leer tus commits privados:
          GITHUB_TOKEN: ${{ secrets.SNAKE_TOKEN }}
          
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          # Este se queda igual porque solo sirve para escribir el resultado en tu repo público
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
